#!/usr/bin/env python

# This script is a simple redirection for the CreateData

from FastNetTool.util import include
#def include(filename):
#  if os.path.exists(filename): 
#    execfile(filename)


# Force CreateData to parseOpts
parseOpts = True
include('FastNetTool/CreateJob.py')
