#!/usr/bin/env python

# This script is a simple redirection for the CreateData
import os
from FastNetTool.util import include
# Force CreateData to parseOpts
parseOpts = True
include('FastNetTool/CreateData.py')
